development:
  aws_access_key_id: AKIAIIXLC4YTMEO4BMNA
  aws_secret_access_key: 5D5clw6fxK76Ac+IcHHDL5RgZpN6+yU6TWJTBfUK
  #salt: your_aws_sdb_proxy_secret_salt_here
  port: 3000

test:
  aws_access_key_id: AKIAIIXLC4YTMEO4BMNA
  aws_secret_access_key: 5D5clw6fxK76Ac+IcHHDL5RgZpN6+yU6TWJTBfUK
  #salt: your_aws_sdb_proxy_secret_salt_here
  port: 3000

production:
  aws_access_key_id: AKIAIIXLC4YTMEO4BMNA
  aws_secret_access_key: 5D5clw6fxK76Ac+IcHHDL5RgZpN6+yU6TWJTBfUK
  #salt: your_aws_sdb_proxy_secret_salt_here
  port: 3000
