development:
  aws_access_key_id: AKIAIERRYQXDX7KCTHPQ
  aws_secret_access_key: r/d8gsBxu1OdRV7Sx8uKWaXU8v2r0asjZho16tUz
  #salt: your_aws_sdb_proxy_secret_salt_here
  port: 3000

test:
  aws_access_key_id: AKIAIERRYQXDX7KCTHPQ
  aws_secret_access_key: r/d8gsBxu1OdRV7Sx8uKWaXU8v2r0asjZho16tUz
  #salt: your_aws_sdb_proxy_secret_salt_here
  port: 3000

production:
  aws_access_key_id: AKIAIERRYQXDX7KCTHPQ
  aws_secret_access_key: r/d8gsBxu1OdRV7Sx8uKWaXU8v2r0asjZho16tUz
  #salt: your_aws_sdb_proxy_secret_salt_here
  port: 3000
