defaults: &defaults
  app_name: Brightpush
  from_email: support@brightpush.in
  base_domain: brightpush.in

  gateway: bogus
  credentials:
    gateway:
      :login: demo
      :password: password
    stripe_publishable_key:
    paypal:
      :login: demo
      :password: password
      :signature: signature
    
development:
  <<: *defaults
  base_domain: brightpushalpha.in # Edit /etc/hosts to add subscriptions.dev, test.subscriptions.dev, etc., or use Pow: http://pow.cx

test:
  <<: *defaults
  from_email: support@brightpushbeta.com
  base_domain: brightpushbeta.in

production:
  <<: *defaults
  credentials:
    gateway:
      :login: demo
      :password: password
    paypal:
      :login: demo
      :password: password
      :signature: signature
  base_domain: brightpush.in    
